# Installs the "ToolTrack Backup" scheduled task.
# It runs backup\run.php every 2 minutes, hidden, as the user who installs it
# (that user must be the one signed in to Google Drive for desktop).
param(
    [string]$PhpExe = '',
    [int]$EveryMinutes = 2
)
$ErrorActionPreference = 'Stop'

$taskName   = 'ToolTrack Backup'
$backupDir  = $PSScriptRoot
$projectDir = Split-Path $backupDir -Parent
$xamppDir   = Split-Path (Split-Path $projectDir -Parent) -Parent    # tooltrack -> htdocs -> xampp
if (-not $PhpExe) { $PhpExe = Join-Path $xamppDir 'php\php.exe' }
$runPhp = Join-Path $backupDir 'run.php'

if (-not (Test-Path $PhpExe)) {
    Write-Host "Could not find XAMPP's php.exe at: $PhpExe" -ForegroundColor Red
    Write-Host "Run again with the right path, e.g.:  install-task.ps1 -PhpExe 'C:\xampp\php\php.exe'"
    exit 1
}

Write-Host ''
Write-Host 'Step 1: checking your setup...' -ForegroundColor Cyan
& $PhpExe $runPhp --check
if ($LASTEXITCODE -ne 0) {
    $answer = Read-Host 'Some checks failed (see above). Install the schedule anyway? (y/N)'
    if ($answer -ne 'y') { Write-Host 'Cancelled. Fix the items above, then run this again.'; exit 1 }
}

Write-Host 'Step 2: creating the hidden launcher...' -ForegroundColor Cyan
$vbs = Join-Path $backupDir 'run-hidden.vbs'
$vbsText = @"
' Generated by install-task.ps1 - runs the backup without a console window.
Set sh = CreateObject("WScript.Shell")
sh.Run """$PhpExe"" ""$runPhp"" --quiet", 0, True
"@
Set-Content -Path $vbs -Value $vbsText -Encoding ASCII

Write-Host "Step 3: registering the scheduled task '$taskName' (every $EveryMinutes minutes)..." -ForegroundColor Cyan
try {
    $action    = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "//B //Nologo `"$vbs`""
    $trigger   = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
                    -RepetitionInterval (New-TimeSpan -Minutes $EveryMinutes) `
                    -RepetitionDuration (New-TimeSpan -Days 3650)
    $settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries `
                    -DontStopIfGoingOnBatteries -MultipleInstances IgnoreNew `
                    -ExecutionTimeLimit (New-TimeSpan -Minutes 30)
    $me        = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    $principal = New-ScheduledTaskPrincipal -UserId $me -LogonType Interactive -RunLevel Limited
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
        -Settings $settings -Principal $principal -Force | Out-Null
    Start-ScheduledTask -TaskName $taskName
} catch {
    Write-Host ''
    Write-Host "Could not create the scheduled task: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host 'Try again by right-clicking Install-Backup.bat and choosing "Run as administrator".'
    exit 1
}

Write-Host ''
Write-Host 'Done. The first backup is starting now.' -ForegroundColor Green
Write-Host 'In a minute or two, double-click Check-Backup.bat to confirm it worked.'
